/**
 * Extended Username Sources (250+ additional platforms)
 * Regional, niche, and specialized platforms
 */

import { UsernameSource } from "./usernameSources";

export const extendedUsernameSources: UsernameSource[] = [
  // ===== REGIONAL SOCIAL NETWORKS (30) =====
  { name: "Odnoklassniki (OK.ru)", url: "https://ok.ru/{username}", category: "social", favicon: "https://ok.ru/favicon.ico" },
  { name: "Mixi", url: "https://mixi.jp/show_friend.pl?id={username}", category: "social" },
  { name: "Douban", url: "https://www.douban.com/people/{username}", category: "social", favicon: "https://www.douban.com/favicon.ico" },
  { name: "Renren", url: "http://www.renren.com/{username}", category: "social" },
  { name: "Cyworld", url: "https://www.cyworld.com/{username}", category: "social" },
  { name: "Orkut Archive", url: "https://orkut.br.com/Main#{username}", category: "social" },
  { name: "Myspace", url: "https://myspace.com/{username}", category: "social", favicon: "https://myspace.com/favicon.ico" },
  { name: "LiveJournal", url: "https://{username}.livejournal.com", category: "social", favicon: "https://www.livejournal.com/favicon.ico" },
  { name: "Blogger", url: "https://{username}.blogspot.com", category: "social", favicon: "https://www.blogger.com/favicon.ico" },
  { name: "WordPress.com", url: "https://{username}.wordpress.com", category: "social", favicon: "https://wordpress.com/favicon.ico" },
  { name: "Ghost", url: "https://{username}.ghost.io", category: "social", favicon: "https://ghost.org/favicon.ico" },
  { name: "Typepad", url: "https://{username}.typepad.com", category: "social" },
  { name: "Xanga", url: "https://xanga.com/profile/{username}", category: "social" },
  { name: "Skyrock", url: "https://{username}.skyrock.com", category: "social" },
  { name: "Hi5", url: "https://www.hi5.com/profile/{username}", category: "social" },
  { name: "Bebo", url: "https://www.bebo.com/{username}", category: "social" },
  { name: "Friendster Archive", url: "https://profiles.friendster.com/{username}", category: "social" },
  { name: "Google+", url: "https://plus.google.com/{username}", category: "social" },
  { name: "Ello", url: "https://ello.co/{username}", category: "social", favicon: "https://ello.co/favicon.ico" },
  { name: "Path", url: "https://path.com/{username}", category: "social" },
  { name: "Diaspora", url: "https://diaspora.social/people/{username}", category: "social" },
  { name: "GNU Social", url: "https://gnusocial.net/{username}", category: "social" },
  { name: "Friendica", url: "https://friendica.social/profile/{username}", category: "social" },
  { name: "Hubzilla", url: "https://hubzilla.org/channel/{username}", category: "social" },
  { name: "Pixelfed", url: "https://pixelfed.social/{username}", category: "social", favicon: "https://pixelfed.social/favicon.ico" },
  { name: "Lemmy", url: "https://lemmy.ml/u/{username}", category: "social" },
  { name: "Kbin", url: "https://kbin.social/u/@{username}", category: "social" },
  { name: "Tildes", url: "https://tildes.net/user/{username}", category: "social" },
  { name: "Hive Social", url: "https://www.hivesocial.app/@{username}", category: "social" },
  { name: "Post News", url: "https://post.news/{username}", category: "social" },
  
  // ===== NICHE COMMUNITIES & HOBBIES (50) =====
  { name: "Steam Workshop", url: "https://steamcommunity.com/id/{username}/myworkshopfiles", category: "gaming" },
  { name: "ModDB", url: "https://www.moddb.com/members/{username}", category: "gaming", favicon: "https://www.moddb.com/favicon.ico" },
  { name: "CurseForge", url: "https://www.curseforge.com/members/{username}", category: "gaming", favicon: "https://www.curseforge.com/favicon.ico" },
  { name: "Planet Minecraft", url: "https://www.planetminecraft.com/member/{username}", category: "gaming" },
  { name: "Nexus Mods", url: "https://www.nexusmods.com/users/{username}", category: "gaming", favicon: "https://www.nexusmods.com/favicon.ico" },
  { name: "GameBanana", url: "https://gamebanana.com/members/{username}", category: "gaming" },
  { name: "SpeedRun.com", url: "https://www.speedrun.com/user/{username}", category: "gaming", favicon: "https://www.speedrun.com/favicon.ico" },
  { name: "Backloggd", url: "https://www.backloggd.com/u/{username}", category: "gaming" },
  { name: "IGN", url: "https://www.ign.com/users/{username}", category: "gaming", favicon: "https://www.ign.com/favicon.ico" },
  { name: "GameFAQs", url: "https://gamefaqs.gamespot.com/community/{username}", category: "gaming", favicon: "https://gamefaqs.gamespot.com/favicon.ico" },
  { name: "Giant Bomb", url: "https://www.giantbomb.com/profile/{username}", category: "gaming", favicon: "https://www.giantbomb.com/favicon.ico" },
  { name: "Grouvee", url: "https://www.grouvee.com/user/{username}", category: "gaming" },
  { name: "HowLongToBeat", url: "https://howlongtobeat.com/user?n={username}", category: "gaming", favicon: "https://howlongtobeat.com/favicon.ico" },
  { name: "Trakt", url: "https://trakt.tv/users/{username}", category: "misc", favicon: "https://trakt.tv/favicon.ico" },
  { name: "TV Time", url: "https://www.tvtime.com/en/user/{username}/profile", category: "misc" },
  { name: "SeriesGuide", url: "https://seriesgui.de/{username}", category: "misc" },
  { name: "IMDb", url: "https://www.imdb.com/user/{username}", category: "misc", favicon: "https://www.imdb.com/favicon.ico" },
  { name: "Rotten Tomatoes", url: "https://www.rottentomatoes.com/user/id/{username}", category: "misc", favicon: "https://www.rottentomatoes.com/favicon.ico" },
  { name: "Metacritic", url: "https://www.metacritic.com/user/{username}", category: "misc", favicon: "https://www.metacritic.com/favicon.ico" },
  { name: "RateYourMusic", url: "https://rateyourmusic.com/~{username}", category: "misc" },
  { name: "Discogs", url: "https://www.discogs.com/user/{username}", category: "misc", favicon: "https://www.discogs.com/favicon.ico" },
  { name: "Rate Your Professor", url: "https://www.ratemyprofessors.com/professor/{username}", category: "misc", favicon: "https://www.ratemyprofessors.com/favicon.ico" },
  { name: "Academia.edu", url: "https://independent.academia.edu/{username}", category: "misc", favicon: "https://www.academia.edu/favicon.ico" },
  { name: "ResearchGate", url: "https://www.researchgate.net/profile/{username}", category: "misc", favicon: "https://www.researchgate.net/favicon.ico" },
  { name: "ORCID", url: "https://orcid.org/{username}", category: "misc", favicon: "https://orcid.org/favicon.ico" },
  { name: "Google Scholar", url: "https://scholar.google.com/citations?user={username}", category: "misc", favicon: "https://scholar.google.com/favicon.ico" },
  { name: "Semantic Scholar", url: "https://www.semanticscholar.org/author/{username}", category: "misc" },
  { name: "ArXiv", url: "https://arxiv.org/search/?searchtype=author&query={username}", category: "misc", favicon: "https://arxiv.org/favicon.ico" },
  { name: "SSRN", url: "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id={username}", category: "misc" },
  { name: "Academia Stack Exchange", url: "https://academia.stackexchange.com/users/{username}", category: "misc" },
  { name: "PhilPapers", url: "https://philpapers.org/profile/{username}", category: "misc" },
  { name: "Mendeley", url: "https://www.mendeley.com/profiles/{username}", category: "misc", favicon: "https://www.mendeley.com/favicon.ico" },
  { name: "Zotero", url: "https://www.zotero.org/{username}", category: "misc", favicon: "https://www.zotero.org/favicon.ico" },
  { name: "Figshare", url: "https://figshare.com/authors/{username}", category: "misc", favicon: "https://figshare.com/favicon.ico" },
  { name: "Zenodo", url: "https://zenodo.org/search?q={username}", category: "misc", favicon: "https://zenodo.org/favicon.ico" },
  { name: "Dryad", url: "https://datadryad.org/stash/profiles/{username}", category: "misc" },
  { name: "OpenReview", url: "https://openreview.net/profile?id={username}", category: "misc" },
  { name: "PubPeer", url: "https://pubpeer.com/search?q={username}", category: "misc" },
  { name: "Publons", url: "https://publons.com/researcher/{username}", category: "misc" },
  { name: "Loop", url: "https://loop.frontiersin.org/people/{username}", category: "misc" },
  { name: "F1000Research", url: "https://f1000research.com/articles/{username}", category: "misc" },
  { name: "BioRxiv", url: "https://www.biorxiv.org/search/{username}", category: "misc" },
  { name: "MedRxiv", url: "https://www.medrxiv.org/search/{username}", category: "misc" },
  { name: "ChemRxiv", url: "https://chemrxiv.org/engage/chemrxiv/public-dashboard/{username}", category: "misc" },
  { name: "PsyArXiv", url: "https://psyarxiv.com/search/?q={username}", category: "misc" },
  { name: "EconPapers", url: "https://econpapers.repec.org/RAS/p{username}.htm", category: "misc" },
  { name: "IDEAS", url: "https://ideas.repec.org/e/p{username}.html", category: "misc" },
  { name: "HubPages", url: "https://hubpages.com/@{username}", category: "misc" },
  { name: "Weebly", url: "https://{username}.weebly.com", category: "misc" },
  { name: "Jimdo", url: "https://{username}.jimdofree.com", category: "misc" },
  
  // ===== FREELANCE & GIG ECONOMY (30) =====
  { name: "99designs", url: "https://99designs.com/profiles/{username}", category: "business", favicon: "https://99designs.com/favicon.ico" },
  { name: "DesignCrowd", url: "https://www.designcrowd.com/designer/{username}", category: "business" },
  { name: "Envato", url: "https://themeforest.net/user/{username}", category: "business", favicon: "https://themeforest.net/favicon.ico" },
  { name: "Creative Market", url: "https://creativemarket.com/{username}", category: "business", favicon: "https://creativemarket.com/favicon.ico" },
  { name: "TemplateMonster", url: "https://www.templatemonster.com/authors/{username}", category: "business" },
  { name: "Crowd Spring", url: "https://www.crowdspring.com/creatives/{username}", category: "business" },
  { name: "Hirable", url: "https://hirable.fyi/{username}", category: "business" },
  { name: "SimplyHired", url: "https://www.simplyhired.com/resumes/{username}", category: "business" },
  { name: "Monster", url: "https://www.monster.com/profile/{username}", category: "business", favicon: "https://www.monster.com/favicon.ico" },
  { name: "Indeed", url: "https://my.indeed.com/p/{username}", category: "business", favicon: "https://www.indeed.com/favicon.ico" },
  { name: "Glassdoor", url: "https://www.glassdoor.com/profile/{username}", category: "business", favicon: "https://www.glassdoor.com/favicon.ico" },
  { name: "Hired", url: "https://hired.com/x/{username}", category: "business" },
  { name: "AngelList Talent", url: "https://angel.co/u/{username}", category: "business" },
  { name: "Dice", url: "https://www.dice.com/dashboard/profiles/{username}", category: "business", favicon: "https://www.dice.com/favicon.ico" },
  { name: "CareerBuilder", url: "https://www.careerbuilder.com/profile/{username}", category: "business" },
  { name: "ZipRecruiter", url: "https://www.ziprecruiter.com/candidate/{username}", category: "business", favicon: "https://www.ziprecruiter.com/favicon.ico" },
  { name: "Remote.co", url: "https://remote.co/remote-workers/{username}", category: "business" },
  { name: "We Work Remotely", url: "https://weworkremotely.com/remote-workers/{username}", category: "business" },
  { name: "FlexJobs", url: "https://www.flexjobs.com/profile/{username}", category: "business" },
  { name: "Remotive", url: "https://remotive.com/remote-workers/{username}", category: "business" },
  { name: "Working Nomads", url: "https://www.workingnomads.co/members/{username}", category: "business" },
  { name: "Remote OK", url: "https://remoteok.com/@{username}", category: "business", favicon: "https://remoteok.com/favicon.ico" },
  { name: "Nomad List", url: "https://nomadlist.com/@{username}", category: "business", favicon: "https://nomadlist.com/favicon.ico" },
  { name: "Remotebase", url: "https://remotebase.com/{username}", category: "business" },
  { name: "Gun.io", url: "https://gun.io/developers/{username}", category: "business" },
  { name: "Turing", url: "https://www.turing.com/developers/{username}", category: "business", favicon: "https://www.turing.com/favicon.ico" },
  { name: "Arc.dev", url: "https://arc.dev/developer/{username}", category: "business" },
  { name: "Terminal", url: "https://terminal.io/developers/{username}", category: "business" },
  { name: "X-Team", url: "https://x-team.com/developers/{username}", category: "business" },
  { name: "Crossover", url: "https://www.crossover.com/candidate/{username}", category: "business" },
  
  // ===== LEARNING & EDUCATION (40) =====
  { name: "Coursera Instructor", url: "https://www.coursera.org/instructor/{username}", category: "misc", favicon: "https://www.coursera.org/favicon.ico" },
  { name: "Udemy Instructor", url: "https://www.udemy.com/user/{username}", category: "misc", favicon: "https://www.udemy.com/favicon.ico" },
  { name: "Skillshare Teacher", url: "https://www.skillshare.com/user/{username}", category: "misc", favicon: "https://www.skillshare.com/favicon.ico" },
  { name: "Teachable", url: "https://{username}.teachable.com", category: "misc" },
  { name: "Thinkific", url: "https://{username}.thinkific.com", category: "misc" },
  { name: "Kajabi", url: "https://{username}.mykajabi.com", category: "misc" },
  { name: "Podia", url: "https://{username}.podia.com", category: "misc" },
  { name: "Gumlet", url: "https://{username}.gumlet.io", category: "misc" },
  { name: "LearnWorlds", url: "https://{username}.learnworlds.com", category: "misc" },
  { name: "Ruzuku", url: "https://{username}.ruzuku.com", category: "misc" },
  { name: "Memrise", url: "https://www.memrise.com/user/{username}", category: "misc", favicon: "https://www.memrise.com/favicon.ico" },
  { name: "Busuu", url: "https://www.busuu.com/user/{username}", category: "misc", favicon: "https://www.busuu.com/favicon.ico" },
  { name: "Babbel", url: "https://www.babbel.com/user/{username}", category: "misc", favicon: "https://www.babbel.com/favicon.ico" },
  { name: "Rosetta Stone", url: "https://www.rosettastone.com/profile/{username}", category: "misc" },
  { name: "italki", url: "https://www.italki.com/teacher/{username}", category: "misc", favicon: "https://www.italki.com/favicon.ico" },
  { name: "Preply", url: "https://preply.com/en/tutor/{username}", category: "misc", favicon: "https://preply.com/favicon.ico" },
  { name: "Verbling", url: "https://www.verbling.com/teachers/{username}", category: "misc" },
  { name: "Cambly", url: "https://www.cambly.com/en/tutors/{username}", category: "misc", favicon: "https://www.cambly.com/favicon.ico" },
  { name: "VIPKid", url: "https://www.vipkid.com/teach/profile/{username}", category: "misc" },
  { name: "Outschool", url: "https://outschool.com/teachers/{username}", category: "misc", favicon: "https://outschool.com/favicon.ico" },
  { name: "TutorMe", url: "https://tutorme.com/tutors/{username}", category: "misc" },
  { name: "Wyzant", url: "https://www.wyzant.com/Tutors/{username}", category: "misc", favicon: "https://www.wyzant.com/favicon.ico" },
  { name: "Chegg Tutors", url: "https://www.chegg.com/tutors/{username}", category: "misc" },
  { name: "Brainly", url: "https://brainly.com/profile/{username}", category: "misc", favicon: "https://brainly.com/favicon.ico" },
  { name: "Course Hero", url: "https://www.coursehero.com/u/{username}", category: "misc", favicon: "https://www.coursehero.com/favicon.ico" },
  { name: "Quizlet", url: "https://quizlet.com/{username}", category: "misc", favicon: "https://quizlet.com/favicon.ico" },
  { name: "StudyBlue", url: "https://www.studyblue.com/users/{username}", category: "misc" },
  { name: "Edmodo", url: "https://www.edmodo.com/profile/{username}", category: "misc" },
  { name: "ClassDojo", url: "https://www.classdojo.com/portfolio/{username}", category: "misc", favicon: "https://www.classdojo.com/favicon.ico" },
  { name: "Seesaw", url: "https://app.seesaw.me/profile/{username}", category: "misc" },
  { name: "Remind", url: "https://www.remind.com/users/{username}", category: "misc", favicon: "https://www.remind.com/favicon.ico" },
  { name: "Schoology", url: "https://app.schoology.com/user/{username}", category: "misc" },
  { name: "Google Classroom", url: "https://classroom.google.com/u/{username}", category: "misc" },
  { name: "Microsoft Teams EDU", url: "https://teams.microsoft.com/edu/{username}", category: "misc" },
  { name: "Canvas LMS", url: "https://canvas.instructure.com/users/{username}", category: "misc" },
  { name: "Blackboard", url: "https://blackboard.com/profile/{username}", category: "misc" },
  { name: "Moodle", url: "https://moodle.org/user/profile.php?id={username}", category: "misc", favicon: "https://moodle.org/favicon.ico" },
  { name: "EdX Profile", url: "https://profile.edx.org/u/{username}", category: "misc" },
  { name: "FutureLearn", url: "https://www.futurelearn.com/profiles/{username}", category: "misc", favicon: "https://www.futurelearn.com/favicon.ico" },
  { name: "LinkedIn Learning", url: "https://www.linkedin.com/learning/instructors/{username}", category: "misc" },
  
  // ===== TECH & ENGINEERING (30) =====
  { name: "AnandTech Forums", url: "https://forums.anandtech.com/members/{username}", category: "forums" },
  { name: "Tom's Hardware", url: "https://forums.tomshardware.com/members/{username}", category: "forums" },
  { name: "Linus Tech Tips Forum", url: "https://linustechtips.com/profile/{username}", category: "forums" },
  { name: "XDA Developers", url: "https://forum.xda-developers.com/m/{username}", category: "forums", favicon: "https://forum.xda-developers.com/favicon.ico" },
  { name: "Android Central", url: "https://forums.androidcentral.com/members/{username}", category: "forums" },
  { name: "iMore Forums", url: "https://forums.imore.com/members/{username}", category: "forums" },
  { name: "MacRumors", url: "https://forums.macrumors.com/members/{username}", category: "forums", favicon: "https://forums.macrumors.com/favicon.ico" },
  { name: "Apple Discussions", url: "https://discussions.apple.com/profile/{username}", category: "forums", favicon: "https://www.apple.com/favicon.ico" },
  { name: "Microsoft Community", url: "https://answers.microsoft.com/en-us/profile/{username}", category: "forums", favicon: "https://www.microsoft.com/favicon.ico" },
  { name: "Ubuntu Forums", url: "https://ubuntuforums.org/member.php?username={username}", category: "forums" },
  { name: "Arch Linux Forums", url: "https://bbs.archlinux.org/profile.php?username={username}", category: "forums" },
  { name: "Fedora Discussion", url: "https://discussion.fedoraproject.org/u/{username}", category: "forums" },
  { name: "Debian User Forums", url: "https://forums.debian.net/memberlist.php?username={username}", category: "forums" },
  { name: "Linux.org", url: "https://www.linux.org/members/{username}", category: "forums" },
  { name: "Unix Stack Exchange", url: "https://unix.stackexchange.com/users/{username}", category: "forums" },
  { name: "Server Fault", url: "https://serverfault.com/users/{username}", category: "forums", favicon: "https://serverfault.com/favicon.ico" },
  { name: "Super User", url: "https://superuser.com/users/{username}", category: "forums", favicon: "https://superuser.com/favicon.ico" },
  { name: "Ask Ubuntu", url: "https://askubuntu.com/users/{username}", category: "forums" },
  { name: "Raspberry Pi Forums", url: "https://forums.raspberrypi.com/memberlist.php?username={username}", category: "forums" },
  { name: "Arduino Forum", url: "https://forum.arduino.cc/u/{username}", category: "forums", favicon: "https://forum.arduino.cc/favicon.ico" },
  { name: "Electronics Stack Exchange", url: "https://electronics.stackexchange.com/users/{username}", category: "forums" },
  { name: "EEVblog Forum", url: "https://www.eevblog.com/forum/index.php?action=profile;username={username}", category: "forums" },
  { name: "SparkFun Forum", url: "https://forum.sparkfun.com/memberlist.php?username={username}", category: "forums" },
  { name: "Adafruit Forums", url: "https://forums.adafruit.com/memberlist.php?username={username}", category: "forums" },
  { name: "Hackaday.io", url: "https://hackaday.io/{username}", category: "dev", favicon: "https://hackaday.io/favicon.ico" },
  { name: "Instructables", url: "https://www.instructables.com/member/{username}", category: "forums", favicon: "https://www.instructables.com/favicon.ico" },
  { name: "Thingiverse", url: "https://www.thingiverse.com/{username}/designs", category: "creative", favicon: "https://www.thingiverse.com/favicon.ico" },
  { name: "Printables", url: "https://www.printables.com/@{username}", category: "creative" },
  { name: "MyMiniFactory", url: "https://www.myminifactory.com/users/{username}", category: "creative" },
  { name: "Cults3D", url: "https://cults3d.com/en/users/{username}", category: "creative" },
  
  // ===== PHOTOGRAPHY & VISUAL ARTS (25) =====
  { name: "Flickr", url: "https://www.flickr.com/people/{username}", category: "creative", favicon: "https://www.flickr.com/favicon.ico" },
  { name: "500px", url: "https://500px.com/p/{username}", category: "creative", favicon: "https://500px.com/favicon.ico" },
  { name: "SmugMug", url: "https://{username}.smugmug.com", category: "creative", favicon: "https://www.smugmug.com/favicon.ico" },
  { name: "Photobucket", url: "https://photobucket.com/user/{username}", category: "creative" },
  { name: "Fotki", url: "https://www.fotki.com/{username}", category: "creative" },
  { name: "Webshots", url: "https://www.webshots.com/user/{username}", category: "creative" },
  { name: "Ipernity", url: "https://www.ipernity.com/home/{username}", category: "creative" },
  { name: "Exposure", url: "https://exposure.co/{username}", category: "creative" },
  { name: "Format", url: "https://{username}.format.com", category: "creative" },
  { name: "Zenfolio", url: "https://{username}.zenfolio.com", category: "creative" },
  { name: "PhotoShelter", url: "https://{username}.photoshelter.com", category: "creative" },
  { name: "Foto.com", url: "https://{username}.foto.com", category: "creative" },
  { name: "Picfair", url: "https://www.picfair.com/{username}", category: "creative", favicon: "https://www.picfair.com/favicon.ico" },
  { name: "ViewBug", url: "https://www.viewbug.com/member/{username}", category: "creative", favicon: "https://www.viewbug.com/favicon.ico" },
  { name: "GuruShots", url: "https://gurushots.com/{username}", category: "creative", favicon: "https://gurushots.com/favicon.ico" },
  { name: "1x.com", url: "https://1x.com/member/{username}", category: "creative" },
  { name: "Photocrowd", url: "https://www.photocrowd.com/{username}", category: "creative" },
  { name: "YouPic", url: "https://youpic.com/photographer/{username}", category: "creative" },
  { name: "EyeEm", url: "https://www.eyeem.com/u/{username}", category: "creative" },
  { name: "VSCO", url: "https://vsco.co/{username}", category: "creative", favicon: "https://vsco.co/favicon.ico" },
  { name: "Glass", url: "https://glass.photo/{username}", category: "creative" },
  { name: "Grainery", url: "https://grainery.com/{username}", category: "creative" },
  { name: "Pixieset", url: "https://{username}.pixieset.com", category: "creative" },
  { name: "Shutterfly", url: "https://{username}.shutterfly.com", category: "creative", favicon: "https://www.shutterfly.com/favicon.ico" },
  { name: "Snapfish", url: "https://www.snapfish.com/home/{username}", category: "creative" },
  
  // ===== WRITING & BLOGGING (30) =====
  { name: "Ghost Blog", url: "https://{username}.ghost.io", category: "forums", favicon: "https://ghost.org/favicon.ico" },
  { name: "WordPress", url: "https://{username}.wordpress.com", category: "forums", favicon: "https://wordpress.com/favicon.ico" },
  { name: "Blogger", url: "https://{username}.blogspot.com", category: "forums", favicon: "https://www.blogger.com/favicon.ico" },
  { name: "Medium", url: "https://medium.com/@{username}", category: "forums", favicon: "https://medium.com/favicon.ico" },
  { name: "Substack", url: "https://{username}.substack.com", category: "forums", favicon: "https://substack.com/favicon.ico" },
  { name: "Ghost", url: "https://{username}.ghost.io", category: "forums" },
  { name: "Beehiiv", url: "https://{username}.beehiiv.com", category: "forums" },
  { name: "ConvertKit", url: "https://{username}.ck.page", category: "forums" },
  { name: "Buttondown", url: "https://buttondown.email/{username}", category: "forums" },
  { name: "Revue", url: "https://www.getrevue.co/profile/{username}", category: "forums" },
  { name: "Telegraph", url: "https://telegra.ph/{username}", category: "forums" },
  { name: "Notion", url: "https://{username}.notion.site", category: "forums", favicon: "https://www.notion.so/favicon.ico" },
  { name: "Coda", url: "https://coda.io/@{username}", category: "forums", favicon: "https://coda.io/favicon.ico" },
  { name: "Airtable Universe", url: "https://airtable.com/universe/user/{username}", category: "forums" },
  { name: "HackMD", url: "https://hackmd.io/@{username}", category: "forums" },
  { name: "Penflip", url: "https://www.penflip.com/{username}", category: "forums" },
  { name: "Scribophile", url: "https://www.scribophile.com/authors/{username}", category: "forums" },
  { name: "Critique Circle", url: "https://www.critiquecircle.com/profile.asp?username={username}", category: "forums" },
  { name: "Absolute Write", url: "https://absolutewrite.com/forums/member.php?username={username}", category: "forums" },
  { name: "Writer's Digest", url: "https://www.writersdigest.com/members/{username}", category: "forums" },
  { name: "National Novel Writing Month", url: "https://nanowrimo.org/participants/{username}", category: "forums" },
  { name: "Reedsy", url: "https://reedsy.com/discovery/user/{username}", category: "forums", favicon: "https://reedsy.com/favicon.ico" },
  { name: "AuthorsDen", url: "https://www.authorsden.com/{username}", category: "forums" },
  { name: "Booksie", url: "https://www.booksie.com/{username}", category: "forums" },
  { name: "Commaful", url: "https://commaful.com/profile/{username}", category: "forums" },
  { name: "Tapas", url: "https://tapas.io/{username}", category: "forums", favicon: "https://tapas.io/favicon.ico" },
  { name: "Royal Road", url: "https://www.royalroad.com/profile/{username}", category: "forums" },
  { name: "ScribbleHub", url: "https://www.scribblehub.com/profile/{username}", category: "forums" },
  { name: "Webnovel", url: "https://www.webnovel.com/profile/{username}", category: "forums" },
  { name: "Inkitt", url: "https://www.inkitt.com/{username}", category: "forums", favicon: "https://www.inkitt.com/favicon.ico" },
  
  // ===== FITNESS & HEALTH (20) =====
  { name: "Strava", url: "https://www.strava.com/athletes/{username}", category: "misc", favicon: "https://www.strava.com/favicon.ico" },
  { name: "MapMyRun", url: "https://www.mapmyrun.com/profile/{username}", category: "misc" },
  { name: "Runkeeper", url: "https://runkeeper.com/user/{username}", category: "misc" },
  { name: "Endomondo", url: "https://www.endomondo.com/users/{username}", category: "misc" },
  { name: "Garmin Connect", url: "https://connect.garmin.com/modern/profile/{username}", category: "misc", favicon: "https://connect.garmin.com/favicon.ico" },
  { name: "Fitocracy", url: "https://www.fitocracy.com/profile/{username}", category: "misc" },
  { name: "Bodybuilding.com", url: "https://forum.bodybuilding.com/member.php?u={username}", category: "forums" },
  { name: "MyFitnessPal", url: "https://www.myfitnesspal.com/profile/{username}", category: "misc", favicon: "https://www.myfitnesspal.com/favicon.ico" },
  { name: "Lose It!", url: "https://www.loseit.com/user/{username}", category: "misc" },
  { name: "Cronometer", url: "https://cronometer.com/friends/{username}", category: "misc" },
  { name: "SparkPeople", url: "https://www.sparkpeople.com/mypage.asp?id={username}", category: "misc" },
  { name: "Fitbit Community", url: "https://community.fitbit.com/t5/user/viewprofilepage/user-id/{username}", category: "misc" },
  { name: "Peloton", url: "https://members.onepeloton.com/members/{username}", category: "misc" },
  { name: "Zwift", url: "https://www.zwift.com/athlete/{username}", category: "misc" },
  { name: "TrainerRoad", url: "https://www.trainerroad.com/app/profile/{username}", category: "misc" },
  { name: "Sufferfest", url: "https://thesufferfest.com/profile/{username}", category: "misc" },
  { name: "Strong App", url: "https://www.strong.app/user/{username}", category: "misc" },
  { name: "JEFIT", url: "https://www.jefit.com/members/profile/{username}", category: "misc" },
  { name: "Hevy", url: "https://hevy.com/{username}", category: "misc" },
  { name: "FitNotes", url: "https://www.fitnotes.com/user/{username}", category: "misc" },
  
  // ===== MISCELLANEOUS & LIFESTYLE (55) =====
  { name: "Goodreads", url: "https://www.goodreads.com/{username}", category: "misc", favicon: "https://www.goodreads.com/favicon.ico" },
  { name: "LibraryThing", url: "https://www.librarything.com/profile/{username}", category: "misc", favicon: "https://www.librarything.com/favicon.ico" },
  { name: "BookBub", url: "https://www.bookbub.com/profile/{username}", category: "misc", favicon: "https://www.bookbub.com/favicon.ico" },
  { name: "Shelfari", url: "https://www.shelfari.com/people/{username}", category: "misc" },
  { name: "Anobii", url: "https://www.anobii.com/{username}", category: "misc" },
  { name: "AllRecipes", url: "https://www.allrecipes.com/cook/{username}", category: "misc", favicon: "https://www.allrecipes.com/favicon.ico" },
  { name: "Food Network", url: "https://www.foodnetwork.com/profiles/{username}", category: "misc", favicon: "https://www.foodnetwork.com/favicon.ico" },
  { name: "Tasty", url: "https://tasty.co/@{username}", category: "misc", favicon: "https://tasty.co/favicon.ico" },
  { name: "Yummly", url: "https://www.yummly.com/profile/{username}", category: "misc", favicon: "https://www.yummly.com/favicon.ico" },
  { name: "BigOven", url: "https://www.bigoven.com/user/{username}", category: "misc" },
  { name: "Epicurious", url: "https://www.epicurious.com/profile/{username}", category: "misc" },
  { name: "Cook Pad", url: "https://cookpad.com/us/users/{username}", category: "misc" },
  { name: "Food52", url: "https://food52.com/users/{username}", category: "misc", favicon: "https://food52.com/favicon.ico" },
  { name: "King Arthur Baking", url: "https://www.kingarthurbaking.com/profile/{username}", category: "misc" },
  { name: "Serious Eats", url: "https://www.seriouseats.com/user/{username}", category: "misc", favicon: "https://www.seriouseats.com/favicon.ico" },
  { name: "Yelp", url: "https://www.yelp.com/user_details?userid={username}", category: "misc", favicon: "https://www.yelp.com/favicon.ico" },
  { name: "Zomato", url: "https://www.zomato.com/{username}", category: "misc", favicon: "https://www.zomato.com/favicon.ico" },
  { name: "OpenTable", url: "https://www.opentable.com/diner/profile/{username}", category: "misc", favicon: "https://www.opentable.com/favicon.ico" },
  { name: "Foursquare", url: "https://foursquare.com/user/{username}", category: "misc", favicon: "https://foursquare.com/favicon.ico" },
  { name: "Untappd", url: "https://untappd.com/user/{username}", category: "misc", favicon: "https://untappd.com/favicon.ico" },
  { name: "Vivino", url: "https://www.vivino.com/users/{username}", category: "misc", favicon: "https://www.vivino.com/favicon.ico" },
  { name: "Delicious", url: "https://del.icio.us/{username}", category: "misc" },
  { name: "Pocket", url: "https://getpocket.com/@{username}", category: "misc", favicon: "https://getpocket.com/favicon.ico" },
  { name: "Instapaper", url: "https://www.instapaper.com/p/{username}", category: "misc", favicon: "https://www.instapaper.com/favicon.ico" },
  { name: "Raindrop.io", url: "https://raindrop.io/user/{username}", category: "misc", favicon: "https://raindrop.io/favicon.ico" },
  { name: "Pinboard", url: "https://pinboard.in/u:{username}", category: "misc", favicon: "https://pinboard.in/favicon.ico" },
  { name: "Diigo", url: "https://www.diigo.com/user/{username}", category: "misc", favicon: "https://www.diigo.com/favicon.ico" },
  { name: "Pearltrees", url: "https://www.pearltrees.com/{username}", category: "misc" },
  { name: "Mix", url: "https://mix.com/{username}", category: "misc" },
  { name: "Flipboard", url: "https://flipboard.com/@{username}", category: "misc", favicon: "https://flipboard.com/favicon.ico" },
  { name: "Feedly", url: "https://feedly.com/i/profile/{username}", category: "misc", favicon: "https://feedly.com/favicon.ico" },
  { name: "Inoreader", url: "https://www.inoreader.com/user/{username}", category: "misc" },
  { name: "NewsBlur", url: "https://newsblur.com/{username}", category: "misc", favicon: "https://newsblur.com/favicon.ico" },
  { name: "The Old Reader", url: "https://theoldreader.com/profile/{username}", category: "misc" },
  { name: "AllTop", url: "https://alltop.com/{username}", category: "misc" },
  { name: "Last.fm", url: "https://www.last.fm/user/{username}", category: "creative", favicon: "https://www.last.fm/favicon.ico" },
  { name: "Ravelry", url: "https://www.ravelry.com/people/{username}", category: "misc", favicon: "https://www.ravelry.com/favicon.ico" },
  { name: "Craftsy", url: "https://www.craftsy.com/profile/{username}", category: "misc" },
  { name: "Pattern Review", url: "https://sewing.patternreview.com/cgi-bin/user.pl?id={username}", category: "misc" },
  { name: "AllFreeSewing", url: "https://www.allfreesewing.com/profile/{username}", category: "misc" },
  { name: "BurdaStyle", url: "https://www.burdastyle.com/profiles/{username}", category: "misc" },
  { name: "Spoonflower", url: "https://www.spoonflower.com/profiles/{username}", category: "creative", favicon: "https://www.spoonflower.com/favicon.ico" },
  { name: "Contrado", url: "https://www.contrado.com/designer/{username}", category: "creative" },
  { name: "Fur Affinity", url: "https://www.furaffinity.net/user/{username}", category: "misc", favicon: "https://www.furaffinity.net/favicon.ico" },
  { name: "Weasyl", url: "https://www.weasyl.com/~{username}", category: "misc" },
  { name: "Inkbunny", url: "https://inkbunny.net/{username}", category: "misc" },
  { name: "SoFurry", url: "https://{username}.sofurry.com", category: "misc" },
  { name: "e621", url: "https://e621.net/users/{username}", category: "nsfw" },
  { name: "F-List", url: "https://www.f-list.net/c/{username}", category: "nsfw" },
  { name: "Omegle Logs", url: "https://logs.omegle.com/{username}", category: "misc" },
  { name: "Chatroulette", url: "https://www.chatroulette.com/{username}", category: "misc" },
  { name: "Ome.tv", url: "https://ome.tv/{username}", category: "misc" },
  { name: "CamSurf", url: "https://camsurf.com/chat/{username}", category: "misc" },
  { name: "Monkey", url: "https://www.monkey.cool/{username}", category: "misc" },
  { name: "Yubo", url: "https://yubo.live/profile/{username}", category: "social" },
  
  // ===== ADDITIONAL GAMING & ESPORTS (30) =====
  { name: "Faceit", url: "https://www.faceit.com/en/players/{username}", category: "gaming", favicon: "https://www.faceit.com/favicon.ico" },
  { name: "ESEA", url: "https://play.esea.net/users/{username}", category: "gaming" },
  { name: "CEVO", url: "https://cevo.com/member/{username}", category: "gaming" },
  { name: "ESL Play", url: "https://play.eslgaming.com/player/{username}", category: "gaming" },
  { name: "Challengermode", url: "https://www.challengermode.com/profile/{username}", category: "gaming" },
  { name: "Toornament", url: "https://www.toornament.com/users/{username}", category: "gaming" },
  { name: "Battlefy", url: "https://battlefy.com/users/{username}", category: "gaming", favicon: "https://battlefy.com/favicon.ico" },
  { name: "Challengermode", url: "https://www.challengermode.com/{username}", category: "gaming" },
  { name: "GamersFirst", url: "https://www.gamersfirst.com/profile/{username}", category: "gaming" },
  { name: "Razer Cortex", url: "https://cortex.razer.com/profile/{username}", category: "gaming" },
  { name: "Discord.me", url: "https://discord.me/user/{username}", category: "gaming" },
  { name: "Disboard", url: "https://disboard.org/user/{username}", category: "gaming" },
  { name: "Top.gg", url: "https://top.gg/user/{username}", category: "gaming" },
  { name: "Mobafire", url: "https://www.mobafire.com/profile/{username}", category: "gaming" },
  { name: "Probuilds", url: "https://www.probuilds.net/pro-player/{username}", category: "gaming" },
  { name: "OP.GG", url: "https://www.op.gg/summoners/na/{username}", category: "gaming", favicon: "https://www.op.gg/favicon.ico" },
  { name: "U.GG", url: "https://u.gg/lol/profile/na1/{username}", category: "gaming" },
  { name: "Porofessor", url: "https://porofessor.gg/profile/na/{username}", category: "gaming" },
  { name: "Mobalytics", url: "https://mobalytics.gg/profile/na/{username}", category: "gaming" },
  { name: "Dotabuff", url: "https://www.dotabuff.com/players/{username}", category: "gaming", favicon: "https://www.dotabuff.com/favicon.ico" },
  { name: "OpenDota", url: "https://www.opendota.com/players/{username}", category: "gaming", favicon: "https://www.opendota.com/favicon.ico" },
  { name: "Stratz", url: "https://stratz.com/players/{username}", category: "gaming" },
  { name: "TrueSkill", url: "https://trueskill.org/player/{username}", category: "gaming" },
  { name: "Gamer Sensei", url: "https://www.gamersensei.com/senseis/{username}", category: "gaming" },
  { name: "Metafy", url: "https://metafy.gg/@{username}", category: "gaming" },
  { name: "ProGuides", url: "https://www.proguides.com/coach/{username}", category: "gaming" },
  { name: "Skill Capped", url: "https://www.skill-capped.com/coach/{username}", category: "gaming" },
  { name: "GamerLink", url: "https://www.gamerlink.gg/user/{username}", category: "gaming" },
  { name: "Guilded", url: "https://www.guilded.gg/profile/{username}", category: "gaming", favicon: "https://www.guilded.gg/favicon.ico" },
  { name: "Medal.tv", url: "https://medal.tv/users/{username}", category: "gaming", favicon: "https://medal.tv/favicon.ico" },
  
  // ===== ADDITIONAL CREATIVE PLATFORMS (20) =====
  { name: "Coub", url: "https://coub.com/{username}", category: "creative", favicon: "https://coub.com/favicon.ico" },
  { name: "Giphy Creator", url: "https://giphy.com/channel/{username}", category: "creative" },
  { name: "Tenor", url: "https://tenor.com/users/{username}", category: "creative", favicon: "https://tenor.com/favicon.ico" },
  { name: "Loom", url: "https://www.loom.com/{username}", category: "creative", favicon: "https://www.loom.com/favicon.ico" },
  { name: "Canva Designer", url: "https://www.canva.com/@{username}", category: "creative" },
  { name: "Figma Community", url: "https://www.figma.com/@{username}", category: "dev", favicon: "https://www.figma.com/favicon.ico" },
  { name: "Adobe Community", url: "https://community.adobe.com/t5/user/viewprofilepage/user-id/{username}", category: "creative" },
  { name: "Procreate Forum", url: "https://folio.procreate.art/{username}", category: "creative" },
  { name: "Clip Studio", url: "https://assets.clip-studio.com/en-us/users/{username}", category: "creative" },
  { name: "ArtRage Gallery", url: "https://www.artrage.com/gallery/{username}", category: "creative" },
  { name: "Krita Artists", url: "https://krita-artists.org/u/{username}", category: "creative" },
  { name: "Blender Artists", url: "https://blenderartists.org/u/{username}", category: "creative" },
  { name: "CGTrader", url: "https://www.cgtrader.com/{username}", category: "creative", favicon: "https://www.cgtrader.com/favicon.ico" },
  { name: "TurboSquid", url: "https://www.turbosquid.com/Search/Artists/{username}", category: "creative" },
  { name: "Unity Asset Store", url: "https://assetstore.unity.com/publishers/{username}", category: "dev", favicon: "https://unity.com/favicon.ico" },
  { name: "Unreal Marketplace", url: "https://www.unrealengine.com/marketplace/profile/{username}", category: "dev" },
  { name: "Itch.io Creator", url: "https://{username}.itch.io", category: "gaming" },
  { name: "GameJolt", url: "https://gamejolt.com/@{username}", category: "gaming", favicon: "https://gamejolt.com/favicon.ico" },
  { name: "IndieDB", url: "https://www.indiedb.com/members/{username}", category: "gaming", favicon: "https://www.indiedb.com/favicon.ico" },
  { name: "Game Developer", url: "https://www.gamedeveloper.com/author/{username}", category: "dev" },
];
