import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Share2, Copy, Check } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import confetti from 'canvas-confetti';
import { supabase } from '@/integrations/supabase/client';

interface DataSource {
  name: string;
  category: string;
  risk_level: string;
  data_found: string[];
  url: string;
}

interface SocialProfile {
  platform: string;
  username: string;
  profile_url: string;
}

interface ComprehensiveReportExportProps {
  scanId: string;
  scan: {
    privacy_score: number;
    total_sources_found: number;
    high_risk_count: number;
    medium_risk_count: number;
    low_risk_count: number;
    created_at: string;
    username?: string;
    email?: string;
    first_name?: string;
    last_name?: string;
  };
  dataSources: DataSource[];
  socialProfiles: SocialProfile[];
}

export const ComprehensiveReportExport = ({
  scanId,
  scan,
  dataSources,
  socialProfiles,
}: ComprehensiveReportExportProps) => {
  const { toast } = useToast();
  const [isExporting, setIsExporting] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const generatePDF = async () => {
    setIsExporting(true);
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();

      // Watermark function
      const addWatermark = () => {
        doc.setFontSize(10);
        doc.setTextColor(200, 200, 200);
        doc.text('Generated by FootprintIQ', pageWidth / 2, pageHeight - 10, { align: 'center' });
      };

      // Page 1: Header & Score
      doc.setFontSize(24);
      doc.setTextColor(99, 102, 241);
      doc.text('Digital Footprint Report', pageWidth / 2, 30, { align: 'center' });

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, 38, { align: 'center' });
      
      if (scan.username || scan.email) {
        doc.text(`Subject: ${scan.username || scan.email}`, pageWidth / 2, 45, { align: 'center' });
      }

      // Privacy Score Circle
      doc.setFontSize(48);
      const scoreColor = scan.privacy_score >= 80 ? [16, 185, 129] : scan.privacy_score >= 60 ? [234, 179, 8] : [239, 68, 68];
      doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
      doc.text(`${scan.privacy_score}`, pageWidth / 2, 75, { align: 'center' });
      
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text('Privacy Score', pageWidth / 2, 85, { align: 'center' });

      // Risk Level
      doc.setFontSize(10);
      const riskText = scan.privacy_score >= 80 
        ? 'Low Risk - Well Protected' 
        : scan.privacy_score >= 60 
        ? 'Medium Risk - Needs Attention' 
        : 'High Risk - Immediate Action Required';
      doc.text(riskText, pageWidth / 2, 95, { align: 'center' });

      // Summary Stats Box
      doc.setFillColor(248, 249, 250);
      doc.rect(20, 105, pageWidth - 40, 40, 'F');
      
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.text('Summary Statistics', 25, 115);
      
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      doc.text(`Total Sources Found: ${scan.total_sources_found}`, 25, 125);
      doc.text(`High Risk: ${scan.high_risk_count}`, 25, 132);
      doc.text(`Medium Risk: ${scan.medium_risk_count}`, 25, 139);
      doc.text(`Low Risk: ${scan.low_risk_count}`, pageWidth / 2 + 10, 125);
      doc.text(`Social Profiles: ${socialProfiles.length}`, pageWidth / 2 + 10, 132);

      addWatermark();

      // Page 2: Risk Distribution Chart (Text representation)
      doc.addPage();
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text('Risk Distribution', 20, 20);

      const total = scan.high_risk_count + scan.medium_risk_count + scan.low_risk_count;
      if (total > 0) {
        doc.setFontSize(10);
        const highPercent = ((scan.high_risk_count / total) * 100).toFixed(1);
        const mediumPercent = ((scan.medium_risk_count / total) * 100).toFixed(1);
        const lowPercent = ((scan.low_risk_count / total) * 100).toFixed(1);

        doc.setFillColor(239, 68, 68);
        doc.rect(20, 30, (scan.high_risk_count / total) * 150, 15, 'F');
        doc.setTextColor(0, 0, 0);
        doc.text(`High Risk: ${highPercent}%`, 180, 40);

        doc.setFillColor(234, 179, 8);
        doc.rect(20, 50, (scan.medium_risk_count / total) * 150, 15, 'F');
        doc.text(`Medium Risk: ${mediumPercent}%`, 180, 60);

        doc.setFillColor(16, 185, 129);
        doc.rect(20, 70, (scan.low_risk_count / total) * 150, 15, 'F');
        doc.text(`Low Risk: ${lowPercent}%`, 180, 80);
      }

      // Data Sources Table
      if (dataSources.length > 0) {
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Data Sources Found', 20, 100);

        const tableData = dataSources.slice(0, 15).map(source => [
          source.name,
          source.category,
          source.risk_level.toUpperCase(),
          source.data_found.slice(0, 2).join(', ') + (source.data_found.length > 2 ? '...' : ''),
        ]);

        autoTable(doc, {
          startY: 105,
          head: [['Source', 'Category', 'Risk', 'Data Found']],
          body: tableData,
          theme: 'grid',
          headStyles: { fillColor: [99, 102, 241], textColor: 255 },
          styles: { fontSize: 8, cellPadding: 2 },
          columnStyles: {
            0: { cellWidth: 40 },
            1: { cellWidth: 35 },
            2: { cellWidth: 20 },
            3: { cellWidth: 65 },
          },
        });
      }

      addWatermark();

      // Page 3: Social Profiles
      if (socialProfiles.length > 0) {
        doc.addPage();
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text('Social Media Profiles', 20, 20);

        const socialData = socialProfiles.slice(0, 20).map(profile => [
          profile.platform,
          profile.username,
          profile.profile_url,
        ]);

        autoTable(doc, {
          startY: 30,
          head: [['Platform', 'Username', 'Profile URL']],
          body: socialData,
          theme: 'striped',
          headStyles: { fillColor: [99, 102, 241], textColor: 255 },
          styles: { fontSize: 8, cellPadding: 2 },
          columnStyles: {
            0: { cellWidth: 30 },
            1: { cellWidth: 40 },
            2: { cellWidth: 90 },
          },
        });

        addWatermark();
      }

      // Page 4: Removal Recommendations
      doc.addPage();
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text('Recommended Actions', 20, 20);

      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      let yPos = 35;

      const recommendations = [
        'Review all high-risk sources and submit removal requests',
        'Update privacy settings on all social media platforms',
        'Enable two-factor authentication on all accounts',
        'Use strong, unique passwords for each account',
        'Regularly monitor your digital footprint for new exposures',
        'Consider using a VPN for sensitive online activities',
        'Review and adjust app permissions on your devices',
        'Be cautious about sharing personal information online',
      ];

      recommendations.forEach((rec, index) => {
        doc.text(`${index + 1}. ${rec}`, 25, yPos);
        yPos += 10;
      });

      // High Priority Sources
      const highRiskSources = dataSources.filter(s => s.risk_level === 'high');
      if (highRiskSources.length > 0) {
        yPos += 10;
        doc.setFontSize(12);
        doc.setTextColor(239, 68, 68);
        doc.text('High Priority Removals', 20, yPos);
        yPos += 10;

        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        highRiskSources.slice(0, 8).forEach(source => {
          doc.text(`• ${source.name} - ${source.category}`, 25, yPos);
          yPos += 7;
        });
      }

      addWatermark();

      // Save PDF
      const fileName = `footprintiq-report-${scanId}-${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);

      // Confetti effect
      confetti({
        particleCount: 100,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#6366f1', '#8b5cf6', '#ec4899'],
      });

      toast({
        title: '🎉 Report Generated!',
        description: 'Your comprehensive report has been downloaded.',
      });
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast({
        title: 'Export Failed',
        description: 'Unable to generate report. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsExporting(false);
    }
  };

  const generateShareLink = async () => {
    try {
      const { data, error } = await supabase.functions.invoke('create-share-link', {
        body: { scanId, expiresInHours: 168 }, // 7 days
      });

      if (error) throw error;

      const fullUrl = `${window.location.origin}/shared/${data.shareToken}`;
      setShareUrl(fullUrl);

      toast({
        title: 'Share Link Created',
        description: 'Your shareable link is ready',
      });
    } catch (error) {
      console.error('Error creating share link:', error);
      toast({
        title: 'Failed to create link',
        description: 'Unable to generate shareable link',
        variant: 'destructive',
      });
    }
  };

  const copyToClipboard = async () => {
    if (!shareUrl) return;

    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      toast({
        title: 'Link Copied!',
        description: 'Share link copied to clipboard',
      });

      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast({
        title: 'Copy Failed',
        description: 'Unable to copy to clipboard',
        variant: 'destructive',
      });
    }
  };

  return (
    <div className="flex gap-2">
      <Button
        onClick={generatePDF}
        disabled={isExporting}
        className="bg-gradient-to-r from-primary to-accent hover:opacity-90 transition-opacity"
      >
        <Download className="w-4 h-4 mr-2" />
        {isExporting ? 'Generating...' : 'Export Report'}
      </Button>

      {!shareUrl ? (
        <Button onClick={generateShareLink} variant="outline">
          <Share2 className="w-4 h-4 mr-2" />
          Get Share Link
        </Button>
      ) : (
        <Button onClick={copyToClipboard} variant="outline">
          {copied ? (
            <>
              <Check className="w-4 h-4 mr-2" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="w-4 h-4 mr-2" />
              Copy Link
            </>
          )}
        </Button>
      )}
    </div>
  );
};
